language: node_js
deploy:
  provider: pages
  repo: smaraf/smaraf.github.io.git
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
