title: smara's place
author: Smaranda Fournier
email: smara1024@gmail.com
description: >-
  A place on the internet to express my technical self. 
  Built with Jekyll and hosted by GitHub pages.
url: "https://smaraf.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smaraof
github_username:  smaraf
linkedin_username: smaranda-fournier

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: UA-113449603-1
show_excerpts: true
